


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."generar_snapshot_cartera"("p_user_id" "uuid", "p_fecha" "date" DEFAULT CURRENT_DATE) RETURNS "uuid"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  v_snapshot_id uuid;
  v_resumen record;
begin
  select *
  into v_resumen
  from public.resumen_cartera_actual
  where user_id = p_user_id;

  if v_resumen is null then
    raise exception 'No existe resumen_cartera_actual para user_id=%', p_user_id;
  end if;

  insert into public.snapshots_cartera (
    id,
    fecha_snapshot,
    valor_total,
    liquidez,
    coste_total,
    pnl_total,
    rentabilidad_total,
    observaciones,
    user_id
  )
  values (
    gen_random_uuid(),
    p_fecha,
    v_resumen.valor_total,
    v_resumen.liquidez,
    v_resumen.coste_total,
    v_resumen.pnl_total_estimado,
    v_resumen.rentabilidad_total_estimada,
    'Snapshot generado desde resumen_cartera_actual',
    p_user_id
  )
  returning id into v_snapshot_id;

  insert into public.snapshot_activos (
    snapshot_id,
    ticker,
    nombre,
    tipo_activo,
    cantidad,
    precio_compra_avg,
    precio_actual,
    valor_posicion,
    peso_cartera,
    pnl,
    rentabilidad,
    user_id
  )
  select
    v_snapshot_id,
    p.ticker,
    p.nombre,
    p.tipo_activo,
    p.cantidad_actual,
    p.precio_compra_avg,
    p.precio_actual,
    p.valor_actual,
    case
      when r.valor_total > 0 then p.valor_actual / r.valor_total
      else 0
    end as peso_cartera,
    p.pnl_no_realizado,
    p.rentabilidad_no_realizada,
    p.user_id
  from public.posiciones_actuales p
  join public.resumen_cartera_actual r
    on r.user_id = p.user_id
  where p.user_id = p_user_id;

  return v_snapshot_id;
end;
$$;


ALTER FUNCTION "public"."generar_snapshot_cartera"("p_user_id" "uuid", "p_fecha" "date") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."generar_snapshots_mensuales_usuario"("p_user_id" "uuid", "p_desde" "date" DEFAULT NULL::"date", "p_hasta" "date" DEFAULT CURRENT_DATE) RETURNS integer
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
declare
  v_inicio date;
  v_cursor date;
  v_fin_mes date;
  v_count integer := 0;
begin
  select coalesce(
    p_desde,
    date_trunc('month', min(fecha))::date,
    date_trunc('month', current_date)::date
  )
  into v_inicio
  from public.movimientos
  where user_id = p_user_id;

  v_cursor := date_trunc('month', v_inicio)::date;

  while v_cursor <= p_hasta loop
    v_fin_mes := (date_trunc('month', v_cursor) + interval '1 month - 1 day')::date;

    if v_fin_mes <= p_hasta then
      if not exists (
        select 1
        from public.snapshots_cartera s
        where s.user_id = p_user_id
          and s.fecha_snapshot = v_fin_mes
      ) then
        perform public.generar_snapshot_cartera(p_user_id, v_fin_mes);
        v_count := v_count + 1;
      end if;
    end if;

    v_cursor := (date_trunc('month', v_cursor) + interval '1 month')::date;
  end loop;

  return v_count;
end;
$$;


ALTER FUNCTION "public"."generar_snapshots_mensuales_usuario"("p_user_id" "uuid", "p_desde" "date", "p_hasta" "date") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."movimientos" (
    "tipo_operacion" "text",
    "ticker" "text",
    "cantidad" double precision DEFAULT '0'::double precision,
    "precio_unidad" double precision DEFAULT '0'::double precision,
    "comision" double precision DEFAULT '0'::double precision,
    "fecha" timestamp with time zone DEFAULT "now"(),
    "importe_liquidez" double precision DEFAULT '0'::double precision,
    "id" bigint NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL
);


ALTER TABLE "public"."movimientos" OWNER TO "postgres";


ALTER TABLE "public"."movimientos" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Movimientos_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."activos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "ticker" "text" NOT NULL,
    "nombre" "text",
    "tipo_activo" "text",
    "cantidad_total" double precision DEFAULT '0'::double precision,
    "precio_compra_avg" double precision DEFAULT '0'::double precision,
    "precio_actual" double precision DEFAULT '0'::double precision,
    "ultima_actualizacion" timestamp with time zone DEFAULT ("now"() AT TIME ZONE 'utc'::"text"),
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "fuente_precio" "text",
    "notas" "text"
);


ALTER TABLE "public"."activos" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."audit_activos_precio_obsoleto" AS
 SELECT "ticker",
    "nombre",
    "tipo_activo",
    "precio_actual",
    "ultima_actualizacion",
    ("now"() - "ultima_actualizacion") AS "antiguedad",
    "user_id"
   FROM "public"."activos"
  WHERE ("ticker" <> 'LIQUIDEZ'::"text");


ALTER VIEW "public"."audit_activos_precio_obsoleto" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."audit_activos_sin_precio" AS
 SELECT "ticker",
    "nombre",
    "tipo_activo",
    "precio_actual",
    "ultima_actualizacion",
    "user_id"
   FROM "public"."activos"
  WHERE (("ticker" <> 'LIQUIDEZ'::"text") AND (("precio_actual" IS NULL) OR ("precio_actual" <= (0)::double precision)));


ALTER VIEW "public"."audit_activos_sin_precio" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."audit_cantidad_descuadrada" AS
 SELECT "m"."user_id",
    "m"."ticker",
    (COALESCE("sum"(
        CASE
            WHEN ("m"."tipo_operacion" = 'Compra'::"text") THEN "m"."cantidad"
            WHEN ("m"."tipo_operacion" = 'Venta'::"text") THEN (- "m"."cantidad")
            ELSE (0)::double precision
        END), (0)::double precision))::numeric AS "cantidad_calculada",
    (COALESCE("a"."cantidad_total", (0)::double precision))::numeric AS "cantidad_en_activos",
    ((COALESCE("sum"(
        CASE
            WHEN ("m"."tipo_operacion" = 'Compra'::"text") THEN "m"."cantidad"
            WHEN ("m"."tipo_operacion" = 'Venta'::"text") THEN (- "m"."cantidad")
            ELSE (0)::double precision
        END), (0)::double precision))::numeric - (COALESCE("a"."cantidad_total", (0)::double precision))::numeric) AS "diferencia"
   FROM ("public"."movimientos" "m"
     LEFT JOIN "public"."activos" "a" ON ((("a"."user_id" = "m"."user_id") AND ("a"."ticker" = "m"."ticker"))))
  WHERE ("m"."ticker" <> 'LIQUIDEZ'::"text")
  GROUP BY "m"."user_id", "m"."ticker", "a"."cantidad_total"
 HAVING ("abs"(((COALESCE("sum"(
        CASE
            WHEN ("m"."tipo_operacion" = 'Compra'::"text") THEN "m"."cantidad"
            WHEN ("m"."tipo_operacion" = 'Venta'::"text") THEN (- "m"."cantidad")
            ELSE (0)::double precision
        END), (0)::double precision))::numeric - (COALESCE("a"."cantidad_total", (0)::double precision))::numeric)) > 0.000001);


ALTER VIEW "public"."audit_cantidad_descuadrada" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."audit_liquidez_descuadrada" AS
 WITH "liquidez_movs" AS (
         SELECT "movimientos"."user_id",
            (COALESCE("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Liquidez'::"text") THEN "movimientos"."importe_liquidez"
                    ELSE (0)::double precision
                END), (0)::double precision))::numeric AS "aportes_liquidez",
            (COALESCE("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Compra'::"text") THEN (("movimientos"."cantidad" * "movimientos"."precio_unidad") + "movimientos"."comision")
                    ELSE (0)::double precision
                END), (0)::double precision))::numeric AS "salidas_por_compras",
            (COALESCE("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Venta'::"text") THEN (("movimientos"."cantidad" * "movimientos"."precio_unidad") - "movimientos"."comision")
                    ELSE (0)::double precision
                END), (0)::double precision))::numeric AS "entradas_por_ventas"
           FROM "public"."movimientos"
          GROUP BY "movimientos"."user_id"
        )
 SELECT "l"."user_id",
    (("l"."aportes_liquidez" - "l"."salidas_por_compras") + "l"."entradas_por_ventas") AS "liquidez_calculada",
    (COALESCE("a"."cantidad_total", (0)::double precision))::numeric AS "liquidez_en_activos",
    ((("l"."aportes_liquidez" - "l"."salidas_por_compras") + "l"."entradas_por_ventas") - (COALESCE("a"."cantidad_total", (0)::double precision))::numeric) AS "diferencia"
   FROM ("liquidez_movs" "l"
     LEFT JOIN "public"."activos" "a" ON ((("a"."user_id" = "l"."user_id") AND ("a"."ticker" = 'LIQUIDEZ'::"text"))));


ALTER VIEW "public"."audit_liquidez_descuadrada" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."posiciones_actuales" AS
 WITH "movs" AS (
         SELECT "movimientos"."user_id",
            "movimientos"."ticker",
            ("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Compra'::"text") THEN "movimientos"."cantidad"
                    WHEN ("movimientos"."tipo_operacion" = 'Venta'::"text") THEN (- "movimientos"."cantidad")
                    ELSE (0)::double precision
                END))::numeric AS "cantidad_actual",
            ("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Compra'::"text") THEN ("movimientos"."cantidad" * "movimientos"."precio_unidad")
                    ELSE (0)::double precision
                END))::numeric AS "capital_comprado_bruto",
            ("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Venta'::"text") THEN ("movimientos"."cantidad" * "movimientos"."precio_unidad")
                    ELSE (0)::double precision
                END))::numeric AS "capital_vendido_bruto",
            ("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = ANY (ARRAY['Compra'::"text", 'Venta'::"text"])) THEN "movimientos"."comision"
                    ELSE (0)::double precision
                END))::numeric AS "comisiones_totales",
            ("count"(*) FILTER (WHERE ("movimientos"."tipo_operacion" = 'Compra'::"text")))::integer AS "n_compras",
            ("count"(*) FILTER (WHERE ("movimientos"."tipo_operacion" = 'Venta'::"text")))::integer AS "n_ventas"
           FROM "public"."movimientos"
          WHERE ("movimientos"."ticker" <> 'LIQUIDEZ'::"text")
          GROUP BY "movimientos"."user_id", "movimientos"."ticker"
        ), "base" AS (
         SELECT COALESCE("a"."user_id", "m"."user_id") AS "user_id",
            COALESCE("a"."ticker", "m"."ticker") AS "ticker",
            COALESCE("a"."nombre", "m"."ticker") AS "nombre",
            "a"."tipo_activo",
            COALESCE("m"."cantidad_actual", (0)::numeric) AS "cantidad_actual",
            (COALESCE("a"."precio_compra_avg", (0)::double precision))::numeric AS "precio_compra_avg",
            (COALESCE("a"."precio_actual", (0)::double precision))::numeric AS "precio_actual",
            "a"."ultima_actualizacion",
            COALESCE("m"."capital_comprado_bruto", (0)::numeric) AS "capital_comprado_bruto",
            COALESCE("m"."capital_vendido_bruto", (0)::numeric) AS "capital_vendido_bruto",
            COALESCE("m"."comisiones_totales", (0)::numeric) AS "comisiones_totales",
            COALESCE("m"."n_compras", 0) AS "n_compras",
            COALESCE("m"."n_ventas", 0) AS "n_ventas"
           FROM ("movs" "m"
             FULL JOIN "public"."activos" "a" ON ((("a"."user_id" = "m"."user_id") AND ("a"."ticker" = "m"."ticker"))))
          WHERE (COALESCE("a"."ticker", "m"."ticker") <> 'LIQUIDEZ'::"text")
        )
 SELECT "user_id",
    "ticker",
    "nombre",
    "tipo_activo",
    "cantidad_actual",
    "precio_compra_avg",
    "precio_actual",
    ("cantidad_actual" * "precio_compra_avg") AS "coste_total_estimado",
    ("cantidad_actual" * "precio_actual") AS "valor_actual",
    (("cantidad_actual" * "precio_actual") - ("cantidad_actual" * "precio_compra_avg")) AS "pnl_no_realizado",
        CASE
            WHEN (("cantidad_actual" * "precio_compra_avg") > (0)::numeric) THEN ((("cantidad_actual" * "precio_actual") - ("cantidad_actual" * "precio_compra_avg")) / ("cantidad_actual" * "precio_compra_avg"))
            ELSE (0)::numeric
        END AS "rentabilidad_no_realizada",
    "capital_comprado_bruto",
    "capital_vendido_bruto",
    "comisiones_totales",
    "n_compras",
    "n_ventas",
    "ultima_actualizacion"
   FROM "base"
  WHERE ("abs"("cantidad_actual") > 0.000001);


ALTER VIEW "public"."posiciones_actuales" OWNER TO "postgres";


CREATE OR REPLACE VIEW "public"."resumen_cartera_actual" AS
 WITH "posiciones" AS (
         SELECT "posiciones_actuales"."user_id",
            "posiciones_actuales"."ticker",
            "posiciones_actuales"."nombre",
            "posiciones_actuales"."tipo_activo",
            "posiciones_actuales"."cantidad_actual",
            "posiciones_actuales"."precio_compra_avg",
            "posiciones_actuales"."precio_actual",
            "posiciones_actuales"."coste_total_estimado",
            "posiciones_actuales"."valor_actual",
            "posiciones_actuales"."pnl_no_realizado",
            "posiciones_actuales"."rentabilidad_no_realizada",
            "posiciones_actuales"."capital_comprado_bruto",
            "posiciones_actuales"."capital_vendido_bruto",
            "posiciones_actuales"."comisiones_totales",
            "posiciones_actuales"."n_compras",
            "posiciones_actuales"."n_ventas",
            "posiciones_actuales"."ultima_actualizacion"
           FROM "public"."posiciones_actuales"
        ), "liq" AS (
         SELECT "activos"."user_id",
            (COALESCE("activos"."cantidad_total", (0)::double precision))::numeric AS "liquidez"
           FROM "public"."activos"
          WHERE ("activos"."ticker" = 'LIQUIDEZ'::"text")
        ), "movs" AS (
         SELECT "movimientos"."user_id",
            (COALESCE("sum"(
                CASE
                    WHEN ("movimientos"."tipo_operacion" = 'Liquidez'::"text") THEN "movimientos"."importe_liquidez"
                    ELSE (0)::double precision
                END), (0)::double precision))::numeric AS "capital_neto_aportado"
           FROM "public"."movimientos"
          GROUP BY "movimientos"."user_id"
        ), "agg" AS (
         SELECT "p"."user_id",
            COALESCE("sum"("p"."coste_total_estimado"), (0)::numeric) AS "coste_total",
            COALESCE("sum"("p"."valor_actual"), (0)::numeric) AS "valor_invertido",
            COALESCE("sum"("p"."pnl_no_realizado"), (0)::numeric) AS "pnl_no_realizado",
            COALESCE("sum"("p"."comisiones_totales"), (0)::numeric) AS "comisiones_totales"
           FROM "posiciones" "p"
          GROUP BY "p"."user_id"
        )
 SELECT "a"."user_id",
    "a"."coste_total",
    "a"."valor_invertido",
    COALESCE("l"."liquidez", (0)::numeric) AS "liquidez",
    ("a"."valor_invertido" + COALESCE("l"."liquidez", (0)::numeric)) AS "valor_total",
    "a"."pnl_no_realizado",
    (("a"."valor_invertido" + COALESCE("l"."liquidez", (0)::numeric)) - COALESCE("m"."capital_neto_aportado", (0)::numeric)) AS "pnl_total_estimado",
        CASE
            WHEN (COALESCE("m"."capital_neto_aportado", (0)::numeric) > (0)::numeric) THEN ((("a"."valor_invertido" + COALESCE("l"."liquidez", (0)::numeric)) - COALESCE("m"."capital_neto_aportado", (0)::numeric)) / "m"."capital_neto_aportado")
            ELSE (0)::numeric
        END AS "rentabilidad_total_estimada",
    "a"."comisiones_totales",
    COALESCE("m"."capital_neto_aportado", (0)::numeric) AS "capital_neto_aportado"
   FROM (("agg" "a"
     LEFT JOIN "liq" "l" ON (("l"."user_id" = "a"."user_id")))
     LEFT JOIN "movs" "m" ON (("m"."user_id" = "a"."user_id")));


ALTER VIEW "public"."resumen_cartera_actual" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."snapshot_activos" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "snapshot_id" "uuid" NOT NULL,
    "ticker" "text" NOT NULL,
    "nombre" "text",
    "tipo_activo" "text",
    "cantidad" numeric(18,8) DEFAULT 0 NOT NULL,
    "precio_compra_avg" numeric(18,8) DEFAULT 0 NOT NULL,
    "precio_actual" numeric(18,8) DEFAULT 0 NOT NULL,
    "valor_posicion" numeric(18,2) DEFAULT 0 NOT NULL,
    "peso_cartera" numeric(10,6) DEFAULT 0 NOT NULL,
    "pnl" numeric(18,2) DEFAULT 0 NOT NULL,
    "rentabilidad" numeric(10,6) DEFAULT 0 NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."snapshot_activos" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."snapshots_cartera" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "fecha_snapshot" "date" NOT NULL,
    "valor_total" numeric(18,2) DEFAULT 0 NOT NULL,
    "liquidez" numeric(18,2) DEFAULT 0 NOT NULL,
    "coste_total" numeric(18,2) DEFAULT 0 NOT NULL,
    "pnl_total" numeric(18,2) DEFAULT 0 NOT NULL,
    "rentabilidad_total" numeric(10,6) DEFAULT 0 NOT NULL,
    "observaciones" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" NOT NULL
);


ALTER TABLE "public"."snapshots_cartera" OWNER TO "postgres";


ALTER TABLE ONLY "public"."activos"
    ADD CONSTRAINT "Activos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."activos"
    ADD CONSTRAINT "Activos_ticker_key" UNIQUE ("ticker");



ALTER TABLE ONLY "public"."movimientos"
    ADD CONSTRAINT "Movimientos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."snapshot_activos"
    ADD CONSTRAINT "snapshot_activos_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."snapshot_activos"
    ADD CONSTRAINT "snapshot_activos_snapshot_id_ticker_key" UNIQUE ("snapshot_id", "ticker");



ALTER TABLE ONLY "public"."snapshots_cartera"
    ADD CONSTRAINT "snapshots_cartera_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."snapshots_cartera"
    ADD CONSTRAINT "snapshots_cartera_user_fecha_key" UNIQUE ("user_id", "fecha_snapshot");



CREATE INDEX "idx_snapshot_activos_snapshot_id" ON "public"."snapshot_activos" USING "btree" ("snapshot_id");



CREATE INDEX "idx_snapshot_activos_ticker" ON "public"."snapshot_activos" USING "btree" ("ticker");



CREATE INDEX "idx_snapshot_activos_user_id" ON "public"."snapshot_activos" USING "btree" ("user_id");



CREATE INDEX "idx_snapshots_cartera_fecha" ON "public"."snapshots_cartera" USING "btree" ("fecha_snapshot" DESC);



CREATE INDEX "idx_snapshots_cartera_user_fecha" ON "public"."snapshots_cartera" USING "btree" ("user_id", "fecha_snapshot" DESC);



CREATE INDEX "idx_snapshots_cartera_user_id" ON "public"."snapshots_cartera" USING "btree" ("user_id");



ALTER TABLE ONLY "public"."activos"
    ADD CONSTRAINT "Activos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."movimientos"
    ADD CONSTRAINT "Movimientos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."snapshot_activos"
    ADD CONSTRAINT "snapshot_activos_snapshot_id_fkey" FOREIGN KEY ("snapshot_id") REFERENCES "public"."snapshots_cartera"("id") ON DELETE CASCADE;



CREATE POLICY "Enable insert for users based on user_id" ON "public"."snapshot_activos" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Enable insert for users based on user_id" ON "public"."snapshots_cartera" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Propietario total" ON "public"."activos" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Propietario total" ON "public"."movimientos" TO "authenticated" USING (("auth"."uid"() = "user_id")) WITH CHECK (("auth"."uid"() = "user_id"));



ALTER TABLE "public"."activos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."movimientos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."snapshot_activos" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."snapshots_cartera" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";






















































































































































GRANT ALL ON FUNCTION "public"."generar_snapshot_cartera"("p_user_id" "uuid", "p_fecha" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."generar_snapshot_cartera"("p_user_id" "uuid", "p_fecha" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."generar_snapshot_cartera"("p_user_id" "uuid", "p_fecha" "date") TO "service_role";



GRANT ALL ON FUNCTION "public"."generar_snapshots_mensuales_usuario"("p_user_id" "uuid", "p_desde" "date", "p_hasta" "date") TO "anon";
GRANT ALL ON FUNCTION "public"."generar_snapshots_mensuales_usuario"("p_user_id" "uuid", "p_desde" "date", "p_hasta" "date") TO "authenticated";
GRANT ALL ON FUNCTION "public"."generar_snapshots_mensuales_usuario"("p_user_id" "uuid", "p_desde" "date", "p_hasta" "date") TO "service_role";


















GRANT ALL ON TABLE "public"."movimientos" TO "anon";
GRANT ALL ON TABLE "public"."movimientos" TO "authenticated";
GRANT ALL ON TABLE "public"."movimientos" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Movimientos_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Movimientos_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Movimientos_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."activos" TO "anon";
GRANT ALL ON TABLE "public"."activos" TO "authenticated";
GRANT ALL ON TABLE "public"."activos" TO "service_role";



GRANT ALL ON TABLE "public"."audit_activos_precio_obsoleto" TO "anon";
GRANT ALL ON TABLE "public"."audit_activos_precio_obsoleto" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_activos_precio_obsoleto" TO "service_role";



GRANT ALL ON TABLE "public"."audit_activos_sin_precio" TO "anon";
GRANT ALL ON TABLE "public"."audit_activos_sin_precio" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_activos_sin_precio" TO "service_role";



GRANT ALL ON TABLE "public"."audit_cantidad_descuadrada" TO "anon";
GRANT ALL ON TABLE "public"."audit_cantidad_descuadrada" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_cantidad_descuadrada" TO "service_role";



GRANT ALL ON TABLE "public"."audit_liquidez_descuadrada" TO "anon";
GRANT ALL ON TABLE "public"."audit_liquidez_descuadrada" TO "authenticated";
GRANT ALL ON TABLE "public"."audit_liquidez_descuadrada" TO "service_role";



GRANT ALL ON TABLE "public"."posiciones_actuales" TO "anon";
GRANT ALL ON TABLE "public"."posiciones_actuales" TO "authenticated";
GRANT ALL ON TABLE "public"."posiciones_actuales" TO "service_role";



GRANT ALL ON TABLE "public"."resumen_cartera_actual" TO "anon";
GRANT ALL ON TABLE "public"."resumen_cartera_actual" TO "authenticated";
GRANT ALL ON TABLE "public"."resumen_cartera_actual" TO "service_role";



GRANT ALL ON TABLE "public"."snapshot_activos" TO "anon";
GRANT ALL ON TABLE "public"."snapshot_activos" TO "authenticated";
GRANT ALL ON TABLE "public"."snapshot_activos" TO "service_role";



GRANT ALL ON TABLE "public"."snapshots_cartera" TO "anon";
GRANT ALL ON TABLE "public"."snapshots_cartera" TO "authenticated";
GRANT ALL ON TABLE "public"."snapshots_cartera" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































drop extension if exists "pg_net";


